### ISSUE TITLE
Evaluation 30 october

### ISSUE THREAD

**Issue by camillethuyentruong** [necrosnake91/Lung_cancer_transcriptome#10] opened 2019-11-03 18:19 UTC
Hi Rodolfo,

Your repo is well-organized and easy to read. I have only made minor English corrections to your README file. Well done! 

If you have some preliminary results already, I suggest you make a "results" folder where you can present the results of your analyses that correspond to your code (figures, graphics). This could later be added as a link for supplementary materials in your future publication.

**Comment by necrosnake91** [comment] 2019-11-03 22:28
Hi Camille,

Thanks a lot for reviewing my repository. I will update the README file with all the suggested corrections as soon as possible. Also, I talked with Alicia the last class because, at this moment, I have some preliminary results from the analysis but I couldn't uploaded for this revision. So, I will upload some plots in a new folder in the upcoming weeks.

Thanks again and have a nice weekend!

**Comment by AliciaMstt** [comment] 2019-11-07 03:32
I agree your README and repo look very good. I only have a minor comment:

Your script 6.Differential_expression_analysis.R contains the line:

```
mydir <- ("/Volumes/Elements/Lung_cancer_transcriptome/OSF_Storage/rsem_output/")
```

This is an absolute path, which as you know is not the best for reproducibility. If you consider this is unavoilable for how you manage your data, please mention in your README that this specific line needs to be changed manually for your scripts to work in other computers.

**Comment by necrosnake91** [comment] 2019-11-08 02:46
Hi Alicia!

Thanks for reviewing my repo. I did not notice the presence of the absolute path in the script. At this moment, I'm finishing to write and test the script and in a few days, I will update it taking in consideration the relative path to the files.

Thanks again and have a nice weekend!

**Comment by AliciaMstt** [comment] 2019-11-08 15:52
Ok, don't forget updating and closing this issue when you correct it.

**Comment by necrosnake91** [comment] 2019-11-12 03:40
Got it!

I have already made the changes to the file.

**Closed by necrosnake91** 2019-11-12 03:40 UTC
